version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  backend:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - "8099:8099"
    stdin_open: true
    tty: true

volumes:
  db: